version: '3.8'

services:
  taro-discord-bot:
    build: 
      context: ./taro-discord-bot/
      dockerfile: Dockerfile
    env_file:
      - .taro-discord-bot-env
    environment:
      - SERVICE_NAME=taro-discord-bot
      - TARO_RUNNER_ENDPOINT=taro-discord-runner:3000
    depends_on:
      taro-discord-runner:
        condition: service_healthy
    restart: always

  taro-discord-controller:
    build: 
      context: ./taro-discord-bot/
      dockerfile: Dockerfile
    env_file:
      - .taro-discord-bot-env
    environment:
      - SERVICE_NAME=taro-discord-controller
    ports:
      - 3000:3000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 20s
      timeout: 1m
      retries: 5
      start_period: 20s
    restart: always

  taro-discord-runner:
    build: 
      context: ./taro-discord-bot/
      dockerfile: Dockerfile
    env_file:
      - .taro-discord-bot-env
    environment:
      - SERVICE_NAME=taro-discord-runner
    ports:
      - 3000:3030
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 20s
      timeout: 1m
      retries: 5
      start_period: 20s
    restart: always
