name: CI

on: [push]

jobs:

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          debug: true
          command_timeout: 200m
          script: 
            cd ./taro-deploy && 
            git fetch --all && 
            git reset --hard origin/master &&
            cd ./taro-discord-bot && 
            git fetch --all &&
            git reset --hard $(cat ../version/taro-discord-bot.txt) && 
            cd .. &&
            sudo docker compose -f "docker-compose.yaml" up -d &&
            sudo docker compose restart taro-discord-bot &&
            echo "Deploy completed!"
            